// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';


function out(param) {
  return /* record */[
          /* id */"test1",
          /* subject */"test2"
        ];
}

function inn(t) {
  return t[/* id */0];
}

exports.out = out;
exports.inn = inn;
/* No side effect */
